# Site settings
title: Industrial Data Analystics Lab
description: Industrial Data Analystics Lab
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Industrial Data Analysis Lab
user_description: Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description--Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-Lab_description-.
user_title:
email:
twitter_username:
github_username:
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
